#!/usr/bin/env zsh

function __source_mac(){
  # init Homebrew
  if [ "$(arch)" = "arm64" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    # emulate arch -x86_64 zsh on arm64
    eval "$(/usr/local/bin/brew shellenv)"
    WINEPREFIX=~/my-game-prefix
    # $(brew --prefix game-porting-toolkit)/bin/wine64 winecfg
  fi

  # Zsh syntax highlighting
  if test -f "$(brew --prefix)"/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh; then
    source "$(brew --prefix)"/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  fi

  # fzf
  command -v fzf &> /dev/null && FZF_VERSION=$(fzf --version | awk '{print $1}')
  if test -n "$FZF_VERSION"; then
    source /opt/homebrew/Cellar/fzf/$FZF_VERSION/shell/completion.zsh
    source /opt/homebrew/Cellar/fzf/$FZF_VERSION/shell/key-bindings.zsh
  fi
}

function __source_arch_linux(){
  # Arch Linux
  if command -v pacman &> /dev/null; then
    # Zsh
    if test -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh; then
      source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    fi
    if test -f /usr/share/fzf/key-bindings.zsh; then
      source /usr/share/fzf/key-bindings.zsh
    fi
    if test -f /usr/share/fzf/completion.zsh; then
      source /usr/share/fzf/completion.zsh
    fi
    if test -f ~/.fzf.zsh; then
      source ~/.fzf.zsh
    fi
  fi
}

# Source custom dotfiles  -  sourced individually to ensure exports.zsh sourced nearly first.
if [ -d ~/.dotfiles/zsh ]; then
    source ~/.dotfiles/zsh/private_functions.zsh
    source ~/.dotfiles/zsh/exports.zsh
    if __is_mac; then
      __source_mac
    elif __is_arch_linux; then
      __source_arch
    fi
    source ~/.dotfiles/zsh/aliases.zsh
    source ~/.dotfiles/zsh/script-aliases.zsh
    source ~/.dotfiles/zsh/functions.zsh
    # source ~/.dotfiles/zsh/toomah-functions.zsh
    source ~/.dotfiles/zsh/wrapper-functions.zsh
    source ~/.dotfiles/zsh/private_functions.zsh  # re-source this so private_functions can access aliases and functions circular-ly.
    source ~/.dotfiles/zsh/setopts.zsh
    source ~/.dotfiles/zsh/completions.zsh
    source ~/.dotfiles/zsh/zstyle.zsh
    source ~/.dotfiles/zsh/keybinds.zsh
    source ~/.dotfiles/zsh/hooks.zsh
    source ~/.dotfiles/zsh/prompt.zsh

    # Source plugins
    source ~/.dotfiles/zsh/plugins/nvm.sh

    # Custom function calls
    if __is_mac; then
        mail -e && info "You have mail!"
    fi
    mkquickcd
    if __is_in_tmux; then
        ve --activate
    fi

    # Custom script calls   -   Use subshell to silence background job output annoyance.
    # (bash $DOTFILES_DIR/scripts/check-connection.sh &)
    # (bash $DOTFILES_DIR/scripts/ls-prs.sh &)
fi


# NOTE: This MUST be evaluated last to avoid some strange edge cases sometimes
typeset -U PATH path # Remove any duplicates in $PATH. Keep $PATH explicit for cross system compatibility reasons.
